name: keystroke-mental
services:
    keystroke-backend-mental:
        stdin_open: true
        tty: true
        ports:
            - 5439:80
            - 7013:443
        environment:
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_HTTPS_PORT=7013
            - ASPNETCORE_Kestrel__Certificates__Default__Password=fabian
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        image: razvanmf/keystroke:backend-copycert
    keystroke-frontend-mental:
        ports:
            - 3000:3000
        image: razvanmf/keystroke:frontend

