name: keystroke-insanity
services:
  keystroke-backend:
    stdin_open: true
    tty: true
    ports:
      - 5439:80
      - 7013:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7013
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fabian
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\Users\Razvan\.aspnet\https:/https/
    image: razvanmf/keystroke:backend
  keystroke-frontend:
    ports:
      - 3000:3000
    image: razvanmf/keystroke:frontend